### ISSUE TITLE
RH value greather than 99 impossible

### ISSUE THREAD

**Issue by sperate** [conurb/low_energy_sensor#3]
There is no verification of the result of this function before setting the value in the oregon frame
lrintf(bme.humidity/1024.0)
Values greater than 99 are impossible to send via oregon protocol : only two BCD quartets for the RH value.
It generates errors : After 99 RH, the value sent is A0 and Domoticz doesn't recognise-it.
Regards,
sperate

**Comment by conurb** [comment]
Although rtl_433 has no issue with 100% RH, you're right and it seems more reliable for all home automation platforms to limit output to 99 (BCD code).

Thank for your feedback
